# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
  
name: Build and deploy Node.js app to Azure Web App - OrticleApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        PORT: '5000'
        SERVER: 'orticle.database.windows.net'
        DATABASE: 'dbOrticle'
        USER: 'publicloginUser'
        PASSWORD: 'pub1.lic2.lo3.gi4.n'
        SEARCH_API_KEY: DD2C87E39EA1C04C45C8989ED8AEB603
        SEARCH_API_ENDPOINT: https://orticlesearch.search.windows.net

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      
      run: |
        npm install
        npm run start

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: .

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'OrticleApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1ef3182e012248538eaf0916b5e9c459 }}
        package: .
